### ISSUE TITLE
the book on github and the book which I download

### ISSUE THREAD

**Issue by raomohsinkhan** [OpenIntroStat/openintro-statistics-slides#8]
hi there,

the book on github openintro-statistic-slides and the book which i download 
OpenIntro Statistics
Fourth Edition

is different?

what is the issue?
chapter names are same, but the content in the chapter is different.

many thanks,
rao

**Comment by mine-cetinkaya-rundel** [comment]
The slides purposefully cover different examples than the book since most students prefer different examples in lecture than the book. The methods presented are the same but the examples and applications are different.
