### ISSUE TITLE
can you please answers the questions in the exercises

### ISSUE THREAD

**Issue by raomohsinkhan** [OpenIntroStat/openintro-statistics-slides#9]
_****_
![exercise_1_35](https://user-images.githubusercontent.com/811377/97457874-f9499700-195b-11eb-861e-690b38807d9d.png)

(a) Are these data collected as part of an
experiment or an observational study?
(b) What is the most common dog name?
What is the most common cat name?
(c) What names are more common for
cats than dogs?
(d) Is the relationship between the two
variables positive or negative? What
does this mean in context of the data?

thank you,
rao

**Comment by mine-cetinkaya-rundel** [comment]
Solutions for odd-numbered exercises are at the end of the book in the Appendix. We do not post solutions for even-numbered exercises however those are available to verified instructors. You can create an account and request verification at https://www.openintro.org/.
